### PR TITLE
Added auto-selecting an exact match during scraping [#1261]

### LINKED ISSUE #1261: Admins can configure scraping to automatically select a perfect match.
As an admin, I would like to enable CX to automatically select an entry if it's the only perfect match found.

### PR DESCRIPTION
**Pull request by mcpierce**
Closes #1261 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by BRUCELLA2 — COMMENTED** [review]
It's ok but i have a comment. I find that you can't see correctly if the toggle is on or off. 
Wouldn't it be interesting to change the colour of the toggle if it is on or off like this: 
toggle-off
toggle-on
with this change in the code : 
    <mat-icon *ngIf='autoSelectExactMatch'
              color='accent'>toggle_on
    </mat-icon>

**Comment by mcpierce** [comment]
> It's ok but i have a comment. I find that you can't see correctly if the toggle is on or off. Wouldn't it be interesting to change the colour of the toggle if it is on or off like this: toggle-off toggle-on with this change in the code : <mat-icon *ngIf='autoSelectExactMatch' color='accent'>toggle_on

That could work. Let me update the PR and push it.

**Comment by mcpierce** [comment]
Hrnn, I took a look and the color didn't really show the difference in state as much as I'd have liked. So I swapped out the radio button on/off icons instead. It shouldn't confuse the user since the tooltip and position should show them which setting is toggled on or off between auto select and confirmation.

**Review by BRUCELLA2 — APPROVED** [review]

**Comment by BRUCELLA2** [comment]
It's ok for me

**Pull request merged**
