### PR TITLE
Changed the scraping confirmation dialog title and message [#415]

### PR DESCRIPTION
**Pull request by mcpierce**
## Status
**READY**

## Migrations
NO

## Description
Changed the english language text for the scraping confirmation dialog box.

### CODE REVIEW

**Review by BRUCELLA2 — CHANGES_REQUESTED** [review]
The Spanish and French translations also need to be updated, don't they? 
(It's not related with this PR but I see some tags are missing in french and spanish comics.json files)

**Comment by mcpierce** [comment]
> The Spanish and French translations also need to be updated, don't they?
> (It's not related with this PR but I see some tags are missing in french and spanish comics.json files)

No, looking at them they didn't appear to be translating the word "scrape" that I could tell.

Which tags are missing? I can fix that with this pr to make things complete.

**Comment by BRUCELLA2** [comment]
In the comics.json in french and spanish, the tag comics-pages is not the same as in english (lines 173 - 182 in french/spanish and lines 173 - 203 in english).
Other things, the tages main-menu -> item -> account is 2 times in common.json in all language.
And the tag users-page -> title and users-page -> text have to be put together i think.

For the translation to update in french and in spanish we don't use the scape word but we use the reference to ComicVine and if we want something generic we can update this.

**Comment by mcpierce** [comment]
> In the comics.json in french and spanish, the tag comics-pages is not the same as in english (lines 173 - 182 in french/spanish and lines 173 - 203 in english).
> Other things, the tages main-menu -> item -> account is 2 times in common.json in all language.
> And the tag users-page -> title and users-page -> text have to be put together i think.
> 
> For the translation to update in french and in spanish we don't use the scape word but we use the reference to ComicVine and if we want something generic we can update this.

Very good. I've gone ahead and addressed those issues in this PR.

**Review by BRUCELLA2 — APPROVED** [review]

**Pull request merged**
