### PR TITLE
Added a comic state machine [#720]

### PR DESCRIPTION
**Pull request by mcpierce**
* Added a backend state machine configuration.
 * Added a column to track the comic's state.

## Status
READY

## Does this PR contain migrations?
YES

## Before You Submit Your PR:
- [X] Have you announced your PR on the comixed-dev mailing list?
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [X] My code follows the code style of this project.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by BRUCELLA2 — DISMISSED** [review]

**Review by BRUCELLA2 — COMMENTED** [review]
Property 'comicState' is missing in library.fixtures.ts : 
206 export const COMIC_1: Comic
247 export const COMIC_2: Comic
288 export const COMIC_3: Comic
329 export const COMIC_4: Comic
370 export const COMIC_5: Comic

**Review by BRUCELLA2 — COMMENTED** [review]
Property 'comicState' is missing in library.fixtures.ts :
206 export const COMIC_1: Comic
247 export const COMIC_2: Comic
288 export const COMIC_3: Comic
329 export const COMIC_4: Comic
370 export const COMIC_5: Comic

**Comment by mcpierce** [comment]
> Property 'comicState' is missing in library.fixtures.ts :
> 206 export const COMIC_1: Comic
> 247 export const COMIC_2: Comic
> 288 export const COMIC_3: Comic
> 329 export const COMIC_4: Comic
> 370 export const COMIC_5: Comic

Okay. I don't see a need for it now, so I've removed knowledge of the comic state from the front end for now.

**Comment by mcpierce** [comment]
@BRUCELLA2 I think this is ready for final review and merge if it's approved.

**Review by BRUCELLA2 — DISMISSED** [review]

**Review by BRUCELLA2 — COMMENTED** [review]
There is still one bug to fix (sonar) and it's ok

**Pull request merged**
