### PR TITLE
Changed the collection page title location [#1250]

### LINKED ISSUE #1250: Move list and collection titles below the toolbar.
The page title being above the toolbar is very visually unappealing.

### PR DESCRIPTION
**Pull request by mcpierce**
Closes #1250 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by BRUCELLA2 — CHANGES_REQUESTED** [review]
It's ok, just conflitcs to resolved.

**Comment by mcpierce** [comment]
> It's ok, just conflitcs to resolved.

Fixed.

**Comment by BRUCELLA2** [comment]
With the new merges, there is a new conflict.

**Comment by mcpierce** [comment]
> With the new merges, there is a new conflict.

This should be fixed and pushed now.

**Review by BRUCELLA2 — APPROVED** [review]

**Pull request merged**
