### PR TITLE
French translation [#333]

### PR DESCRIPTION
**Pull request by BRUCELLA2**
## Status
**READY**

## Migrations
NO

## Description
Added french translation

### CODE REVIEW

**Review by mcpierce — CHANGES_REQUESTED** [review]
Can you squash this commit into the other so it's a single commit?

**Comment by mcpierce** [comment]
This all looks good. Once the second commit is squashed into the first I'll merge it.

**Comment by BRUCELLA2** [comment]
Squash done

**Review by mcpierce — COMMENTED** [review]
I'm having trouble getting the translation to load. I believe there's an issue in one of the interpolated values, but haven't figured out which one yet. I see this error when I switch to French:

```
core.js:4002 ERROR n {message: "Expected "=", "}", or identifier but end of input found.", expected: Array(3), found: null, location: {…}, name: "SyntaxError", …}
```

but haven't determined which entry it is.

Are you able to use the French translation locally?

**Comment by BRUCELLA2** [comment]
I found the mistake. I also adjusted the size of the main menu to the size of the text (it was out of range with the French translation).

**Review by mcpierce — APPROVED** [review]
Looks great and works on my system.

**Pull request merged**
