### PR TITLE
Added using english as the reference language [#1193]

### LINKED ISSUE #1193: English is the reference translation fileset.
As a translation contributor, I want to provide a complete translation for each release. To do this, I would like to take the english translation, copy it into the appropriate directory, and translate the entries to my target language.

### PR DESCRIPTION
**Pull request by mcpierce**
Closes #1193 

## Status
READY

## Does this PR contain migrations?
NO

## Before You Submit Your PR:
- [ ] Have you announced your PR on the comixed-dev mailing list?
- [X] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactors existing code (code changes for efficiency or maintainability)
- [ ] Security fix (be sure to include the CVE in the commit message) 
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by BRUCELLA2** [comment]
If I understand correctly the purpose of this PR is to add a new language to Comixed. It's a good idea to have an option to not have all the languages available and only the relevant ones.
On the other hand, I'm not sure that leaving the translation entirely up to the user (administrator) is a good idea. It would be less work for the team but I'm not sure that many users will have the courage to translate everything.
Maybe we should make a repository with a directory for each version and a subdirectory for each language with the translation files that could be retrieved and updated by the community for example.

**Comment by mcpierce** [comment]
> If I understand correctly the purpose of this PR is to add a new language to Comixed. It's a good idea to have an option to not have all the languages available and only the relevant ones. On the other hand, I'm not sure that leaving the translation entirely up to the user (administrator) is a good idea. It would be less work for the team but I'm not sure that many users will have the courage to translate everything. Maybe we should make a repository with a directory for each version and a subdirectory for each language with the translation files that could be retrieved and updated by the community for example.

I'm not sure I follow what you're saying. We would move the translations to an external project? How would we integrate the translation back into the main code?

**Comment by BRUCELLA2** [comment]
Um, I think I went a bit far in my head. Forget about creating a repository ....
But I still think it's not a good thing to delete the different translations even if it means extra work. I'm committed to doing the French at least ;)

**Comment by mcpierce** [comment]
> Um, I think I went a bit far in my head. Forget about creating a repository .... But I still think it's not a good thing to delete the different translations even if it means extra work. I'm committed to doing the French at least ;)

Understood. I'll decline this PR then and close the ticket.

**Pull request closed without merging**
